# Generated by Django 3.1.4 on 2020-12-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('detail', models.TextField()),
                ('precout', models.TextField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('next_visit_date', models.CharField(max_length=100)),
            ],
        ),
    ]
