# Generated by Django 3.1.4 on 2020-12-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201220_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='about',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
